name: CI

on: [push]

jobs:
  build-packages:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 3
      matrix:
        # platform: [mips_24kc, mipsel_24kc, aarch64_cortex-a53, aarch64_cortex-a72, arm_cortex-a9_vfpv3-d16, mips_4kec, mips_mips32, mipsel_24kc_24kf, mipsel_74kc, mipsel_mips32, mips64_octeonplus, powerpc_464fp, powerpc_8540, aarch64_generic, arc_archs, arm_arm926ej-s, arm_arm1176jzf-s_vfp, arm_cortex-a15_neon-vfpv4, arm_cortex-a5_vfpv4, arm_cortex-a7, arm_cortex-a7_neon-vfpv4, arm_cortex-a8_vfpv3, arm_cortex-a9, arm_cortex-a9_neon, arm_fa526, arm_mpcore, arm_xscale, x86_64, i386_pentium4, i386_pentium-mmx]
        platform: [arm_cortex-a9_vfpv3-d16]
        include:
          - sdk_url: https://downloads.openwrt.org/releases/23.05.2/targets/mvebu/cortexa9/openwrt-sdk-23.05.2-mvebu-cortexa9_gcc-12.3.0_musl_eabi.Linux-x86_64.tar.xz
            platform: arm_cortex-a9_vfpv3-d16
            upload_name: ps3netsrv_arm_cortex-a9_vfpv3-d16
            build_path: openwrt-sdk-23.05.2-mvebu-cortexa9_gcc-12.3.0_musl_eabi.Linux-x86_64
    steps:
    - uses: actions/checkout@v1
    - name: build packages
      run: |
        cd $HOME
        sudo apt-get update
        sudo apt-get install -y \
        build-essential \
        curl \
        file \
        gawk \
        gettext \
        git \
        libncurses5-dev \
        libssl-dev \
        python2.7 \
        python3 \
        rsync \
        subversion \
        sudo \
        swig \
        unzip \
        wget \
        zlib1g-dev
        wget -c ${{ matrix.sdk_url }}
        tar xf $(basename "${{ matrix.sdk_url }}")
        cd $(basename "${{ matrix.sdk_url }}" .tar.xz)
        echo $USIGN_SECRET | base64 -d > key-build
        echo "src-git udpbd_feed https://github.com/spammerofspam/ps3netsrv-openwrt" >> feeds.conf.default
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make defconfig
        make package/udpbd-server/download V=s
        make package/udpbd-server/prepare V=s
        make package/udpbd-server/compile V=s
      env:
        USIGN_SECRET: ${{ secrets.USIGN_SECRET }}
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ${{ matrix.upload_name }}
        path: /home/runner/${{ matrix.build_path }}/bin/packages/${{ matrix.platform }}/udpbd_feed/
